name: learn-telegram-actions
on: [push]
jobs:
  send-telegram-message:
    runs-on: ubuntu-latest
    steps:
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: 806567508
        token: 1745032824:AAHlK2UlsX1JIcy2I48vFExw-nJfwQwg84w
        args: The ${{ github.event_name }} event triggered first step.
